# Generated by Django 2.2.4 on 2019-08-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='fastcampus_order',
        ),
    ]
